# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  publish = "."
  # the root website directory
  command = "echo 'I be building' "
  # the build command
  
[[redirects]]
  from = "/api/ron/*"
  to = "https://ron-swanson-quotes.herokuapp.com/v2/:splat"
  status = 200
  
